-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_users
(
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    password_hash character varying(200) NOT NULL,
    role character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.disliked_restaurants
(
    user_id integer,
    restaurant_id integer
);

CREATE TABLE IF NOT EXISTS public.images
(
    image_id integer NOT NULL,
    file_name character varying(200),
    mime_type character varying(100),
    file_size integer,
    file_blob bytea,
    active boolean
);

CREATE TABLE IF NOT EXISTS public.liked_restaurants
(
    user_id integer,
    restaurant_id integer
);

CREATE TABLE IF NOT EXISTS public.match_history
(
    match_id integer NOT NULL,
    user_id integer,
    restaurant_id integer,
    matched_at timestamp without time zone,
    selected boolean,
    PRIMARY KEY (match_id)
);

CREATE TABLE IF NOT EXISTS public.restaurant
(
    restaurant_id integer NOT NULL,
    name character varying(250) NOT NULL,
    cuisine character varying(250) NOT NULL,
    price_range numeric(10, 0) NOT NULL,
    latitude numeric(10, 6) NOT NULL,
    longitude numeric(10, 6) NOT NULL,
    address character varying(250) NOT NULL,
    photo_url character varying(255),
    reviews text,
    PRIMARY KEY (restaurant_id)
);

CREATE TABLE IF NOT EXISTS public.user_profile
(
    user_id integer NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(200) NOT NULL,
    password character varying(200) NOT NULL,
    preferences text,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_restaurant_match
(
    match_id integer NOT NULL,
    user_id integer,
    restaurant_id integer,
    swipe_direction character varying(8),
    PRIMARY KEY (match_id)
);

ALTER TABLE public.disliked_restaurants
    ADD FOREIGN KEY (restaurant_id)
    REFERENCES public.restaurant (restaurant_id)
    NOT VALID;


ALTER TABLE public.disliked_restaurants
    ADD FOREIGN KEY (user_id)
    REFERENCES public.user_profile (user_id)
    NOT VALID;


ALTER TABLE public.liked_restaurants
    ADD FOREIGN KEY (restaurant_id)
    REFERENCES public.restaurant (restaurant_id)
    NOT VALID;


ALTER TABLE public.liked_restaurants
    ADD FOREIGN KEY (user_id)
    REFERENCES public.user_profile (user_id)
    NOT VALID;


ALTER TABLE public.match_history
    ADD FOREIGN KEY (restaurant_id)
    REFERENCES public.restaurant (restaurant_id)
    NOT VALID;


ALTER TABLE public.match_history
    ADD FOREIGN KEY (user_id)
    REFERENCES public.user_profile (user_id)
    NOT VALID;


ALTER TABLE public.user_restaurant_match
    ADD FOREIGN KEY (restaurant_id)
    REFERENCES public.restaurant (restaurant_id)
    NOT VALID;


ALTER TABLE public.user_restaurant_match
    ADD FOREIGN KEY (user_id)
    REFERENCES public.user_profile (user_id)
    NOT VALID;

END;